#ifndef CORE_ALERT_MANAGER_H
#define CORE_ALERT_MANAGER_H

#include "core/DataTypes.h"
#include <algorithm>
#include <map>
#include <mutex>
#include <string>
#include <vector>

namespace core {

struct AlertManagerParams {
  int cooldown_seconds = 5;
  size_t max_history_size = 10000;
  size_t cleanup_threshold = 8000;
  double cleanup_ratio = 0.5;
};

/**
 * @class AlertManager
 * @brief Manages alert deduplication, cooldowns, and prioritization.
 */
class AlertManager {
public:
  explicit AlertManager(const AlertManagerParams& params = {})
      : cooldown_us_(static_cast<uint64_t>(params.cooldown_seconds) * 1000000ULL),
        max_history_size_(params.max_history_size),
        cleanup_threshold_(params.cleanup_threshold),
        cleanup_ratio_(params.cleanup_ratio) {}

  /**
   * @brief Filters and processes raw alerts.
   * @param raw_alerts The alerts generated by rules this frame.
   * @return The final list of alerts to be emitted.
   */
  std::vector<Alert> processAlerts(const std::vector<Alert> &raw_alerts) {
    std::lock_guard<std::mutex> lock(m_mutex_);
    std::vector<Alert> final_alerts;
    uint64_t current_time_us = 0;

    // Sort by priority: smaller value = higher priority (0 > 1 > 2)
    auto sorted_alerts = raw_alerts;
    std::sort(sorted_alerts.begin(), sorted_alerts.end(),
              [](const Alert &a, const Alert &b) {
                return a.priority_ < b.priority_; // Ascending: smaller priority first (higher priority)
              });

    for (const auto &alert : sorted_alerts) {
      current_time_us = alert.timestamp_; // Same unit as EventMeta::timestamp_ (microseconds).

      // Cooldown Check
      if (isInCooldown(alert.dedup_key_, current_time_us)) {
        continue;
      }

      // Deduplication Logic
      updateCooldown(alert.dedup_key_, current_time_us);
      final_alerts.push_back(alert);
    }

    const bool over_soft_limit =
        (cleanup_threshold_ > 0) && (alert_history_.size() > cleanup_threshold_);
    const bool over_hard_limit =
        (max_history_size_ > 0) && (alert_history_.size() > max_history_size_);

    // History cleanup (stale entries + size limits)
    if (over_soft_limit || over_hard_limit) {
      cleanupHistory(current_time_us);
    }

    return final_alerts;
  }

private:
  std::map<std::string, uint64_t> alert_history_;
  std::mutex m_mutex_;
  uint64_t cooldown_us_;
  size_t max_history_size_;
  size_t cleanup_threshold_;
  double cleanup_ratio_;

  bool isInCooldown(const std::string& key, uint64_t now_us) {
    auto it = alert_history_.find(key);
    if (it == alert_history_.end()) return false;
    return (now_us - it->second) < cooldown_us_;
  }

  void updateCooldown(const std::string& key, uint64_t now_us) {
    alert_history_[key] = now_us;
  }

  void cleanupHistory(uint64_t now_us) {
    if (alert_history_.empty()) {
      return;
    }

    // 1) Drop entries that are already outside the cooldown window.
    // They are not needed anymore and can be safely removed.
    if (now_us > 0 && cooldown_us_ > 0) {
      for (auto it = alert_history_.begin(); it != alert_history_.end();) {
        const uint64_t ts = it->second;
        const bool known_order = (ts <= now_us);
        const bool expired =
            known_order && ((now_us - ts) >= cooldown_us_);
        if (expired) {
          it = alert_history_.erase(it);
        } else {
          ++it;
        }
      }
    }

    // 2) Determine the desired size after cleanup.
    size_t desired_size = alert_history_.size();

    // Hard cap.
    if (max_history_size_ > 0 && desired_size > max_history_size_) {
      desired_size = max_history_size_;
    }

    // Optional extra cleanup when crossing the soft threshold.
    if (cleanup_threshold_ > 0 && alert_history_.size() > cleanup_threshold_) {
      if (cleanup_ratio_ > 0.0 && cleanup_ratio_ < 1.0) {
        const size_t ratio_target = static_cast<size_t>(
            static_cast<double>(alert_history_.size()) * (1.0 - cleanup_ratio_));
        if (ratio_target < desired_size) {
          desired_size = ratio_target;
        }
      } else if (cleanup_ratio_ >= 1.0) {
        desired_size = 0;
      }
    }

    const size_t current = alert_history_.size();
    if (desired_size >= current) {
      return;
    }

    // 3) Evict oldest entries by timestamp (LRU-ish) to satisfy size target.
    std::vector<std::pair<uint64_t, std::string>> entries;
    entries.reserve(alert_history_.size());
    for (const auto& kv : alert_history_) {
      entries.push_back(std::make_pair(kv.second, kv.first));
    }

    std::sort(entries.begin(), entries.end(),
              [](const std::pair<uint64_t, std::string>& a,
                 const std::pair<uint64_t, std::string>& b) {
                return a.first < b.first;
              });

    const size_t to_remove = current - desired_size;
    for (size_t i = 0; i < to_remove && i < entries.size(); ++i) {
      alert_history_.erase(entries[i].second);
    }
  }
};

} // namespace core

#endif // CORE_ALERT_MANAGER_H
